# Generated by Django 5.2.15 on 2026-06-16 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DOCUMENT_UPLOADED', 'Document uploaded'), ('DOCUMENT_DELETED', 'Document deleted'), ('DOCUMENT_REVIEW_STARTED', 'Document review started'), ('DOCUMENT_APPROVED', 'Document approved'), ('DOCUMENT_REJECTED', 'Document rejected')], max_length=80)),
                ('entity', models.CharField(max_length=80)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['entity', 'entity_id'], name='audits_audi_entity_689d9e_idx'), models.Index(fields=['action'], name='audits_audi_action_a590ed_idx'), models.Index(fields=['created_at'], name='audits_audi_created_61fc5f_idx')],
            },
        ),
    ]
