# Generated by Django 5.2.15 on 2026-06-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('DOCUMENT_UPLOADED', 'Document uploaded'), ('DOCUMENT_DELETED', 'Document deleted'), ('DOCUMENT_REVIEW_STARTED', 'Document review started'), ('DOCUMENT_APPROVED', 'Document approved'), ('DOCUMENT_REJECTED', 'Document rejected'), ('DOCUMENT_VERIFICATION_SUCCEEDED', 'Document verification succeeded'), ('DOCUMENT_VERIFICATION_FAILED', 'Document verification failed')], max_length=80),
        ),
    ]
