# Generated by Django 5.2.15 on 2026-06-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
